# -*- coding: utf-8 -*-
"""DAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zTN1k5Pn9O2dadgZUsoI27OexULBBqas
"""

import numpy as np
# creating arrays
arr=np.array([1,2,3,4,5])
print(arr)

arr1=np.zeros((3,3),dtype=int)
print(arr1)

arr2=np.ones((2,2),dtype=int)
print(arr2)

ran=np.arange(10)
print(ran)

#Array manipulation
arr3=arr.reshape(5,1)
print(arr3)

#slicing of array
arr4=arr[2:4]
print(arr4)

#stacking of array
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.vstack(a+b)
print(c)

#stacking horizontally
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.stack(a+b)
print(c)

#splitting
a=np.array([1,2,3,4,5,6])
b=np.split(a,3)
print(b)

#Transpose matrix
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a.T
print(b)

#addition of two arrays
array1=np.array([1,2,3,4,5])
array2=np.array([5,4,3,2,1])
result=array1+array2
print(result)

#broadcasting
array1=np.array([1,2,3,4,5])
print(array1+3)

#dot product
a=np.array([[1,2],[2,3]])
b=np.array([[3,4],[4,5]])
c=np.dot(a,b)
print(c)
#eigen value & vector
d=np.linalg.eig(c)
print(d)

#using axis
import numpy as np
a=np.array([[1,2,3],[2,3,4]])
d=np.sum(a)
print(d)
b=np.array([[2,3,4],[3,4,5]])
c=np.sum(a+b)
print(c)
a=np.array([[1,2,3],
 [2,3,4]])
d=np.sum(a,axis=0)
e=np.sum(a,axis=1)
print(d)
print(e)

#statistical operations
a=np.array([1,2,3,4,5])
b=np.mean(a)
c=np.median(a)
d=np.var(a)
e=np.std(a)
print(b)
print(c)
print(d)
print(e)

#creating ,loading and using a data set
data=np.loadtxt("/content/soc_number_file.txt")
print(data)
data1=np.loadtxt("/content/soc_number_file.txt",dtype=int)
print(data1)
data2=np.savetxt("/content/soc_num_file",data)
print(data2)

#plotting data methods
import  matplotlib.pyplot as plt
a=np.array([1,2,3,4,5,6,7,8,9,10])
plt.plot(a)

#Day2
#basic program of pandas
import pandas as pd
a=['Jwalitha','Ramya','Durga','Jahnavi','Lahari','Sunny','Dhanush']
r=pd.Series(a,index=[67,43,44,89,34,45,23])
print(r)

#Loading csv file
a=pd.read_csv("/content/larger_sales_dataset.csv")
a.shape
print(a)
print(a.loc[1])
b=a['Quantity'].mean
a=a.fillna(b)
print(a)

#Dropping duplicates
a=pd.read_csv("/content/larger_sales_dataset2.csv")
a=a.drop_duplicates()
print(a)

#loading a text file
a=pd.read_csv("/content/New Text Document.txt",sep=" ")
print(a)

#Loading a xlsx file
a=pd.read_excel("/content/Historicalinvesttemp.xlsx",sheet_name=0)
print(a)
a.shape

a=pd.read_csv("/content/larger_sales_dataset.csv")
a.head(5)
a.tail(10)

from google.colab import drive
drive.mount("/content/drive")

#Dropping last 10 lines in another file
import pandas as pd
a=pd.read_csv("/content/larger_sales_dataset.csv")
a.shape
testing1=a.tail(10)
for i in range(9990,9980,-1):
  a.drop([i],axis=0,inplace=True)
  testing1.to_csv("manual_testing1.csv")
print(testing1.groupby(['Product Category'])['Quantity'].count())

#plotting using scatter
import numpy as np
import matplotlib.pyplot as plt
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.scatter(runs,w,color='orange')
plt.title('IndvsAus_score')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
#generate an array of 200 values between -pi & pi
tigar=np.linspace(-2*np.pi, 2*np.pi, 100)
print(tigar)
plt.plot(tigar, np.sin(tigar) ,color='black')
plt.title("sin(x)")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
overs=np.arange(5,50,5)
overs_a=np.arange(5,30,5)
runs_i=np.array([25,51,84,131,160,189,220,250,267])
runs_a=np.array([15,41,94,110,151])
wickets=np.array([12,32,96])
plt.subplot(2,1,2)
plt.plot(overs,runs_i,color='blue',label='India')
plt.legend(loc='best')
plt.subplot(2,1,1)
plt.plot(overs_a,runs_a,color='yellow',label='Aus')
plt.legend(loc='best')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
a=[230,560,780,127,128]
b=[200,160,270,127,400]
years=[1,2,3,4]
profit_a=[(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b=[(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth='3',label='company A',marker='>',ms='15',mec='k')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label='company B',marker='H')

a=np.array([25,60,5,20])
labe=["AIML","python","pandas","numpy"]
colors=('blue','black','pink','red')
sizes=[15,15,15,15]
fontsize=15
explo=[0.2,0,0,0]
plt.pie(a,labels=labe,explode=explo,startangle=180,textprops={'fontsize':fontsize},shadow='true')
plt.show()

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.scatterplot(x="total_bill",y="tip",data=tips)
plt.title("scatter plot of Total Bill vs. Tip")
plt.xlabel("Total Bill($)")
plt.ylabel("Tips($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.violinplot(x="day",y="total_bill",data=tips)
plt.title("scatter plot of Total Bill vs. Day")
plt.xlabel("Total Bill($)")
plt.ylabel("Day of the week")
plt.show()

import seaborn as plt
import matplotlib.pyplot as plt
#load example dataset
iris=sns.load_dataset("iris")
print(iris)
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation Heatmap of Iris Dataset")
plt.show()

import seaborn as plt
import matplotlib.pyplot as plt
#load example dataset
anagrams=sns.load_dataset("anagrams")
print(anagrams)
correlation_matrix=anagrams.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation Heatmap of anagrams Dataset")
plt.show()