# -*- coding: utf-8 -*-
"""DAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zTN1k5Pn9O2dadgZUsoI27OexULBBqas
"""

import numpy as np
#creating arrays
arr=np.array([1,2,3,4,5])
print(arr)
arr1=np.zeros((3,3),dtype=int)
print(arr1)
arr2=np.ones((2,2),dtype=int)
print(arr2)
ran=np.arange(10)
print(ran)

"""# New Section"""

#array multiplication
arr3=arr.reshape(5,1)
print(arr3)

#silicing
arr4=arr[2:4]
print(arr4)

#stacking of an array
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.vstack(a+b)
print(c)

a=np.array([[1,2,3],[3,4,5]])

import numpy as np
a=np.array([[3,2,1],[2,3,6]])
d=np.sum(a)
print(d)
b=np.array([[2,3,6],[3,6,5]])
c=np.sum(a+b)
print(c)
a=np.array([[1,2,3],[2,3,4]])
d=np.sum(a,axis=0)
e=np.sum(a,axis=1)
print(d,e)

a=np.array([[1,2],[2,3]])
b=np.array([[3,4],[4,5]])
c=np.dot(a,b)
print(c)

#eigen value&vector





array1=np.array([1,2,3,4,5])
array2=np.array([5,4,3,2,1])
result=array1+array2
print(result)

a=np.array([1,2,3,4])
b=np.split(a,2)
print(b)

a=np.array([[1,2,3,4],[5,6,7,8]])
b=a.T
print(b)



data=np.loadtxt("/content/number.txt")
print(data)
data1=np.loadtxt("/content/number.txt",dtype=int)
print(data1)
data2=np.savetxt("/content/number",data)
print(data2)

#plotting data methods
import  matplotlib.pyplot as plt
a=np.array([1,2,3,4,5,6,7,8,9,10])
plt.plot(a)

import pandas as pd
a=["jwalitha","ramya",'durga','jahnavi','sathwika','poojitha']
r=pd.Series(a,index=[67,45,15,34,67,77])
print(r)
a=pd.read_csv("/content/cr_tweets.csv")
print(a)
print(a.loc[1])
a=a.fillna(b)
print(a)





a=pd.read_csv("/content/cr_tweets.csv")
a.shape
testing2=a.tail(10)
for i in range(794,784,-1):
  a.drop([i],axis=0,inplace=True)
  testing2.to_csv("manual_testing2.csv")
print(testing2.groupby(['id'])['reweet'].count())

a=pd.read_csv("/content/New Text Document.txt",sep=" ")
print(a)

a=pd.read_excel("/content/cr-tweets.xlsx",sheet_name=0)
print(a)
a.shape

#plotting using scatter
import numpy as np
import matplotlib.pyplot as plt
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.scatter(runs,w,color='orange')
plt.title('IndvsAus_score')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
#generate an array of 200 values between -pi & pi
tigar=np.linspace(-2*np.pi, 2*np.pi, 100)
print(tigar)
plt.plot(tigar, np.sin(tigar) ,color='black')
plt.title("sin(x)")
plt.show()

import numpy as mp
import matplotlib.pyplot as plt
overs=np.arange(5,50,5)
overs_a=np.arange(5,30,5)
runs_i=np.array([25,51,84,131,160,189,220,250,267])
runs_a=np.array([15,41,94,110,151])
wickets=np.array([12,32,96])
plt.plot(overs,runs_i,color='blue',label='India')
plt.plot(overs_a,runs_a,color='yellow',label='Aus')
plt.legend(loc='best')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
a=[230,560,780,127,128]
b=[200,160,270,127,400]
years=[1,2,3,4]
profit_a=[(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b=[(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth='3',label='company A',marker='>',ms='15',mec='k')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label='company B',marker='H')

a=np.array([25,60,5,20])
labe=["AIML","python","pandas","numpy"]
colors=('blue','black','pink','red')
sizes=[15,15,15,15]
fontsize=15
explo=[0.2,0,0,0]
plt.pie(a,labels=labe,explode=explo,startangle=180,textprops={'fontsize':fontsize},shadow='true')
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
d=pd.read_csv("/content/jan_month_temp.csv")
print(d)

average_temperature=d['temp'].mean()
highest_temperature=d['temp'].max()
lowest_temperature=d['temp'].min()
threshold=27
days_above_threshold=d[d['temp']>threshold].shape[0]

print("Average temperature for the month:",average_temperature)
print("Highest temperature for the month:",highest_temperature)
print("Lowest temperature for the month:",lowest_temperature)
print("Number of days temperature exceeded",threshold,"degree celsius:",days_above_threshold)

d.plot(kind='line',color='black')
plt.title('jan month temp')
plt.xlabel('days')
plt.ylabel('temp')

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.scatterplot(x="total_bill",y="tip",data=tips)
plt.title("scatter plot of Total Bill vs. Tip")
plt.xlabel("Total Bill($)")
plt.ylabel("Tips($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.violinplot(x="day",y="total_bill",data=tips)
plt.title("scatter plot of Total Bill vs. Day")
plt.xlabel("Total Bill($)")
plt.ylabel("Day of the week")
plt.show()

import seaborn as plt
import matplotlib.pyplot as plt
#load example dataset
iris=sns.load_dataset("iris")
print(iris)
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation Heatmap of Iris Dataset")
plt.show()

import seaborn as plt
import matplotlib.pyplot as plt
#load example dataset
anagrams=sns.load_dataset("anagrams")
print(anagrams)
correlation_matrix=anagrams.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation Heatmap of anagrams Dataset")
plt.show()

