# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mdTP53quJUfaeGFHEh1oFioSt-7tgMEk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
d=pd.read_csv("/content/jan_month_temp.csv")
print(d)

average_temperature=d['temp'].mean()
highest_temperature=d['temp'].max()
lowest_temperature=d['temp'].min()
threshold=27
days_above_threshold=d[d['temp']>threshold].shape[0]

print("Average temperature for the month:",average_temperature)
print("Highest temperature for the month:",highest_temperature)
print("Lowest temperature for the month:",lowest_temperature)
print("Number of days temperature exceeded",threshold,"degree celsius:",days_above_threshold)

d.plot(kind='line',color='black')
plt.title('jan month temp')
plt.xlabel('days')
plt.ylabel('temp')